/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DebriefRouteImport } from './routes/debrief'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as WebRouteImport } from './routes/web'
import { Route as ApiAttachmentLookupRouteImport } from './routes/api/attachment-lookup'
import { Route as ApiLabsRouteImport } from './routes/api/labs'
import { Route as ApiProgressRouteImport } from './routes/api/progress'
import { Route as ApiLabsIdRouteImport } from './routes/api/labs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DebriefRoute = DebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentLookupRoute = ApiAttachmentLookupRouteImport.update({
  id: '/api/attachment-lookup',
  path: '/api/attachment-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsRoute = ApiLabsRouteImport.update({
  id: '/api/labs',
  path: '/api/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsIdRoute = ApiLabsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debrief': typeof DebriefRoute
  '/engine': typeof EngineRoute
  '/lab': typeof LabRoute
  '/labs': typeof LabsRoute
  '/progress': typeof ProgressRoute
  '/web': typeof WebRoute
  '/api/attachment-lookup': typeof ApiAttachmentLookupRoute
  '/api/labs': typeof ApiLabsRouteWithChildren
  '/api/progress': typeof ApiProgressRoute
  '/api/labs/$id': typeof ApiLabsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debrief': typeof DebriefRoute
  '/engine': typeof EngineRoute
  '/lab': typeof LabRoute
  '/labs': typeof LabsRoute
  '/progress': typeof ProgressRoute
  '/web': typeof WebRoute
  '/api/attachment-lookup': typeof ApiAttachmentLookupRoute
  '/api/labs': typeof ApiLabsRouteWithChildren
  '/api/progress': typeof ApiProgressRoute
  '/api/labs/$id': typeof ApiLabsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debrief': typeof DebriefRoute
  '/engine': typeof EngineRoute
  '/lab': typeof LabRoute
  '/labs': typeof LabsRoute
  '/progress': typeof ProgressRoute
  '/web': typeof WebRoute
  '/api/attachment-lookup': typeof ApiAttachmentLookupRoute
  '/api/labs': typeof ApiLabsRouteWithChildren
  '/api/progress': typeof ApiProgressRoute
  '/api/labs/$id': typeof ApiLabsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/debrief'
    | '/engine'
    | '/lab'
    | '/labs'
    | '/progress'
    | '/web'
    | '/api/attachment-lookup'
    | '/api/labs'
    | '/api/progress'
    | '/api/labs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/debrief'
    | '/engine'
    | '/lab'
    | '/labs'
    | '/progress'
    | '/web'
    | '/api/attachment-lookup'
    | '/api/labs'
    | '/api/progress'
    | '/api/labs/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/debrief'
    | '/engine'
    | '/lab'
    | '/labs'
    | '/progress'
    | '/web'
    | '/api/attachment-lookup'
    | '/api/labs'
    | '/api/progress'
    | '/api/labs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DebriefRoute: typeof DebriefRoute
  EngineRoute: typeof EngineRoute
  LabRoute: typeof LabRoute
  LabsRoute: typeof LabsRoute
  ProgressRoute: typeof ProgressRoute
  WebRoute: typeof WebRoute
  ApiAttachmentLookupRoute: typeof ApiAttachmentLookupRoute
  ApiLabsRoute: typeof ApiLabsRouteWithChildren
  ApiProgressRoute: typeof ApiProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debrief': {
      id: '/debrief'
      path: '/debrief'
      fullPath: '/debrief'
      preLoaderRoute: typeof DebriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachment-lookup': {
      id: '/api/attachment-lookup'
      path: '/api/attachment-lookup'
      fullPath: '/api/attachment-lookup'
      preLoaderRoute: typeof ApiAttachmentLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs': {
      id: '/api/labs'
      path: '/api/labs'
      fullPath: '/api/labs'
      preLoaderRoute: typeof ApiLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/$id': {
      id: '/api/labs/$id'
      path: '/$id'
      fullPath: '/api/labs/$id'
      preLoaderRoute: typeof ApiLabsIdRouteImport
      parentRoute: typeof ApiLabsRoute
    }
  }
}

interface ApiLabsRouteChildren {
  ApiLabsIdRoute: typeof ApiLabsIdRoute
}

const ApiLabsRouteChildren: ApiLabsRouteChildren = {
  ApiLabsIdRoute: ApiLabsIdRoute,
}

const ApiLabsRouteWithChildren =
  ApiLabsRoute._addFileChildren(ApiLabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DebriefRoute: DebriefRoute,
  EngineRoute: EngineRoute,
  LabRoute: LabRoute,
  LabsRoute: LabsRoute,
  ProgressRoute: ProgressRoute,
  WebRoute: WebRoute,
  ApiAttachmentLookupRoute: ApiAttachmentLookupRoute,
  ApiLabsRoute: ApiLabsRouteWithChildren,
  ApiProgressRoute: ApiProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
